### ISSUE TITLE
Request for Public Dataset Access

### ISSUE THREAD

**Issue by HUMDRFGRY** [exitudio/GaitSADA#1]
Hello, I'm very interested in your research. May I ask if the dataset is publicly available?

**Comment by exitudio** [comment]
Hi,
  Thank you for interest in our work. The dataset is still under review by Institutional Review Boards (IRBs). Once, it is approved we will release it ASAP.

**Comment by David-92589** [comment]
Hello，Could you kindly provide an update on its approval status?
If the dataset has been cleared for release, would it be possible to share the timeline for public availability? I’m very interested in accessing it for research purposes and would greatly appreciate any updates.
